language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: java-script
    name: TypeScript / ESLint / Tests
    script:
    #- "npm outdated"
    # - "npm run lint"
    - "npm run typecheck"
    - "npm test"
